### ISSUE TITLE
suffixes = '_trans.obj' if category == 'mug' else '.obj'

### ISSUE THREAD

**Issue by Bingo-1996** [swords123/SSC-6D#3]
Hi, author. I saw dataset_real.py uses '_trans.obj' for _mug_ instead of  the original  '.obj' file provided by NOCS.  How to obtain that file, and what's the difference between these two files?
In addition, can you provide the training code of DeepSDF?

**Comment by swords123** [comment]
I just uploaded the mug model file that I have processed in [here](https://github.com/swords123/SSC-6D/tree/main/data).
We translate the original mug model so that the center of its  body is the origin. The model points is not used durning training and just used for testing.  You can remove relative code directly.

We use the DeepSDF for training each category separately using the synthetic models in the obj_models folder of NOCS dataset (the "obj_models/train" folder). The config file of training DeepSDF for each category is on the param folder (the "speces.json" file). And the split file for training each category is [split.zip](https://github.com/swords123/SSC-6D/files/8440117/split.zip)

The mug category should be translated so that the center of its  body is the origin when training DeepSDF.

**Comment by Bingo-1996** [comment]
Got it! I will try it, thank you very much

**Comment by swords123** [comment]
I remember that we made a small change to the original DeepSDF when preprocessing the data, you can refer to these codes for modification [src.zip](https://github.com/swords123/SSC-6D/files/8470782/src.zip). The main modification is in "src/Utils cpp".  I'm very sorry I just remembered it. If you have any other questions, please let me know.

**Comment by Bingo-1996** [comment]
Hi~ I haven't retrain DeepSDF yet. I am just trying to run train_pre.py and train_all.py for all categories. But when I pretrain the  bottle category, I faced the 'Dataset Error ' problem as declared in the dataset_sym.py. Other categories are OK.
Is there any special operation for bottle?
In addition, are there any other operations for the mug category besides replacing the obj files? Because the performance of mug I trained is much worse than that reported in the paper. I'm not sure if I need to modify some parameters.

**Comment by swords123** [comment]
The 'Dataset Error ' problem as declared in the dataset_sym.py means there is no bottle instance in the loaded image. You can print the image path to find which image cause this problem and delete this image in the split file (param/bottle_remv/sym_train_bottle_remv_sampled_list.txt). However, I've tested split file and it shouldn't have such a problem. You can check it and please let me know what causes this problem. 

![Uploading 2022-04-14 17-44-05屏幕截图.png…]()
For the mug category, this is the result for six experiment, we use the average as the final reslut in our paper. What is the result you have getted.

**Comment by swords123** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns="http://www.w3.org/TR/REC-html40">
<head>

<meta name=Generator content="Microsoft Excel">

<style>

</style>
</head>
<body>



  |   |   |   |   |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
mug | 3D#25 |   | 99.64117 | 99.42699 | 99.64117 | 99.64117 | 99.64117 | 99.64117 |   | 99.60547333
3D#50 |   | 91.49878 | 81.80255 | 92.33866 | 92.56573 | 84.07193 | 77.49524 |   | 86.628815
3D#75 |   | 16.75357 | 9.16309 | 21.42563 | 10.79448 | 11.52984 | 7.4164 |   | 12.84716833
5d2cm |   | 1.6315 | 1.01505 | 2.10956 | 1.22267 | 0.6547 | 0.49921 |   | 1.188781667
5d5cm |   | 2.12877 | 1.09837 | 2.42663 | 1.50268 | 0.84054 | 0.70715 |   | 1.45069
10d2cm |   | 15.25318 | 7.49016 | 18.95577 | 13.13209 | 7.7194 | 2.01256 |   | 10.76052667
10d5cm |   | 17.53221 | 9.02933 | 21.49109 | 14.80765 | 8.88247 | 2.87145 |   | 12.4357
10d10cm |   | 17.53221 | 9.02933 | 21.49109 | 14.80765 | 8.88247 | 2.87145 |   | 12.4357



</body>

</html>
mug	[3D#25](mailto:3D@25)		99.64117	99.42699	99.64117	99.64117	99.64117	99.64117		99.60547333
	3D#50		91.49878	81.80255	92.33866	92.56573	84.07193	77.49524		86.628815
	3D#75		16.75357	9.16309	21.42563	10.79448	11.52984	7.4164		12.84716833
	5d2cm		1.6315	1.01505	2.10956	1.22267	0.6547	0.49921		1.188781667
	5d5cm		2.12877	1.09837	2.42663	1.50268	0.84054	0.70715		1.45069
	10d2cm		15.25318	7.49016	18.95577	13.13209	7.7194	2.01256		10.76052667
	10d5cm		17.53221	9.02933	21.49109	14.80765	8.88247	2.87145		12.4357
	10d10cm		17.53221	9.02933	21.49109	14.80765	8.88247	2.87145		12.4357

**Comment by swords123** [comment]
The 'Dataset Error ' problem as declared in the dataset_sym.py means there is no bottle instance in the loaded image. You can print the image path to find which image cause this problem and delete this image in the split file (param/bottle_remv/sym_train_bottle_remv_sampled_list.txt). However, I've tested split file and it shouldn't have such a problem. You can check it and please let me know what causes this problem.

There is no other operation for the mug category and the obj file will not affect the performance. For the mug category, this are the results for six experiments, we use the average as the final reslut in our paper. What is the performance you have getted.

<html xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns="http://www.w3.org/TR/REC-html40">
<head>

<meta name=Generator content="Microsoft Excel">


</head>
<body>



  |   |   1| 2 | 3 | 4 | 5 | 6 |   | average  |     |
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
3D#25 |   | 99.64117 | 99.42699 | 99.64117 | 99.64117 | 99.64117 | 99.64117 |   | 99.60547333
3D#50 |   | 91.49878 | 81.80255 | 92.33866 | 92.56573 | 84.07193 | 77.49524 |   | 86.628815
3D#75 |   | 16.75357 | 9.16309 | 21.42563 | 10.79448 | 11.52984 | 7.4164 |   | 12.84716833
5d2cm |   | 1.6315 | 1.01505 | 2.10956 | 1.22267 | 0.6547 | 0.49921 |   | 1.188781667
5d5cm |   | 2.12877 | 1.09837 | 2.42663 | 1.50268 | 0.84054 | 0.70715 |   | 1.45069
10d2cm |   | 15.25318 | 7.49016 | 18.95577 | 13.13209 | 7.7194 | 2.01256 |   | 10.76052667
10d5cm |   | 17.53221 | 9.02933 | 21.49109 | 14.80765 | 8.88247 | 2.87145 |   | 12.4357
10d10cm |   | 17.53221 | 9.02933 | 21.49109 | 14.80765 | 8.88247 | 2.87145 |   | 12.4357



</body>

</html>

**Comment by swords123** [comment]
Do you have WeChat, I think it is more convenient. My WeChat is qq1136558142.
