### ISSUE TITLE
explain structure of the SDF model

### ISSUE THREAD

**Issue by rpc-group** [swords123/SSC-6D#4]
Thanks a lot for sharing an interesting work!

Could you please explain how the [param](https://drive.google.com/file/d/17z1U9kP_Vu1yVpHb_JGedINDNVsQOTka/view?usp=sharing) constructed? 

How to generate files and subdirectories in the `param` directory?  Based on the readme file I understood that it's used to train the DeepSDF decoder. But I saw a .pth in the `ModelParameters` directory.  Could you give some info on that file?

**Comment by swords123** [comment]
In the "param" file, the "specs.json" is the config file for training the DeepSDF decoder, which is similar with the [released code of Deepsdf](https://github.com/facebookresearch/DeepSDF/blob/main/examples/chairs/specs.json). The .pth in the ModelParameters directory is the trained model weight for the DeepSDF decoder. The training process is also similar with [Deepsdf](https://github.com/facebookresearch/DeepSDF). The .pkl is the generated latent code for the synthetic dataset after training the DeepSDF.
